#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  creationTimestamp: null
  labels:
    app: couchdb
  name: couchdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: couchdb
  serviceName: couchdb-server
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: couchdb
    spec:
      volumes:
        - name: couchdb-config
          configMap:
            name: couchdb-config
      hostname: couchdb
      securityContext:
        fsGroup: 5984
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - image: couchdb:latest
        imagePullPolicy: IfNotPresent
        ports:
          - name: couchdb-port
            protocol: TCP
            containerPort: 5984
        securityContext:
          runAsUser: 5984
          runAsGroup: 5984
        name: couchdb
        env:
        - name: DB_URL
          value: 'http://localhost:5984/member_db'
        - name: COUCHDB_USER
          value: 'cdbadmin'
        - name: COUCHDB_PASSWORD
          value: 'secret'
        volumeMounts:
          - name: couchdb-config
            mountPath: /opt/couchdb/etc/local.d/config.ini
            subPath: config.ini
          - mountPath: /opt/couchdb/data
            name: couchdb-vol
        resources: {}
  volumeClaimTemplates:
  - metadata:
      name: couchdb-vol
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 4Gi
