#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: uni-resolver-driver-did-uport
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-resolver-driver-did-uport
  template:
    metadata:
      labels:
        app: uni-resolver-driver-did-uport
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: uni-resolver-driver-did-uport
        image: uni-resolver-driver-did-uport:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 8081
            protocol: TCP
            name: http-port
        resources: {}
status: {}
