#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: uni-registrar-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uni-registrar-web
  template:
    metadata:
      labels:
        app: uni-registrar-web
    spec:
      volumes:
        - name: config
          configMap:
            name: uni-registrar-web-config
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: uni-registrar-web
        image: uni-registrar-web:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
            protocol: TCP
            name: http-port
        livenessProbe:
          httpGet:
            path: /
            port: http-port
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 5
        volumeMounts:
          - name: config
            mountPath: /opt/uni-registrar-java/uni-registrar-web/config.json
            subPath: config.json
        resources: {}
status: {}
