#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: driver-did-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: driver-did-v1
  template:
    metadata:
      labels:
        app: driver-did-v1
    spec:
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      containers:
      - name: driver-did-v1
        image: driver-did-v1:latest
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 9080
            protocol: TCP
            name: http-port
        resources: {}
status: {}
